@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

title Диаграмма компонентов для Интернет бибилотеки

Container(spa, "Single-Page App", "TypeScript, React Native", "Представляет собой весь функционал для пользователя в Web-браузере")
Container(ma, "Mobile App", "TypeScript, React Native", "Представляет собой весь функционал для пользователя в мобильной версии приложения")
ContainerDb(db, "Database", "MySQL", "База данных содеражащая список книг, список пользователей")
System_Ext(mbs, "Общий функционал системы", "Представляет собой запись общей информации о аккаунтах, книгах, их взятии и т.д.")

Container_Boundary(api, "Приложение") {
    Component(sign, "Контроллер входа", "MVC Rest Controlle", "Контроллер для входа каждого пользователя Интернет библиотеки")
    Component(accounts, "Контроллер для книг", "MVC Rest Controlle", "Представляет пользователям общее описание всех книг")
    Component(security, "Компонент безопасности", "Spring Bean", "Представляет собой функционал для входа, смены пароля и т.д.")
    Component(mbsfacade, "Внешняя оболочка общего функционала", "Spring Bean", "Фасад на основной функционал библиотеки")

    Rel(sign, security, "Uses")
    Rel(accounts, mbsfacade, "Uses")
    Rel(security, db, "Считывание и запись в БД", "JDBC")
    Rel(mbsfacade, mbs, "Uses", "XML/HTTPS")
}

Rel(spa, sign, "Uses", "JSON")
Rel(spa, accounts, "Uses", "JSON")

Rel(ma, sign, "Uses", "JSON")
Rel(ma, accounts, "Uses ", "JSON")
@enduml
