@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

title Диаграмма компонентов для Интернет бибилотеки

Container(spa, "Приложение для администрирования библиотеки", "TypeScript, React Native", "Представляет собой весь функционал для пользователя в Web-браузере")
Container(ma, "Приложение для читателей", "TypeScript, React Native", "Представляет собой весь функционал для пользователя для назначения книги на пользователя в мобильной версии приложения")
ContainerDb(db, "Database", "MySQL", "База данных, содержащая в себе необходимые данные - список книг, список пользователей")

Container_Boundary(api, "Общий функционал системы") {
    Component(security, "Компонент безопасности", "ASP.Net", "Представляет собой функционал для входа, смены пароля и т.д.")
    Component(mbsfacade, "Внешняя оболочка для отображения функционала взаиможействия с книгами", "ASP.Net", "Фасад на основной функционал библиотеки")
    Component(accfacade, "Оболочка для отображения информации о пользователе","ASP.Net", "Отображение информации о пользователе")
    
    Container_Boundary(core, "Ядро") {
    Component(sign, "Контроллер авторизации", "ASP.Net", "Контроллер для авторизации каждого пользователя в Интернет библиотеку")
    Component(books, "Контроллер взаимодействия с книгами", "ASP.Net", "Представляет пользователям общую информацию о всех книгах")
    Component(accounts, "Контроллер пользователей", "ASP.Net", "Контроллер для обзора информации о пользователе")
    }
    Rel(accounts, accfacade, "Uses")
    Rel(accfacade, accounts, "Uses")
    Rel(security, db, "Считывание и запись в БД", "JDBC")
    Rel(mbsfacade, db, "Считывание и запись в БД", "JDBC")
    Rel(accfacade, db, "Считывание и запись в БД", "JDBC")
    Rel(sign, security, "Uses")
    Rel(books, mbsfacade, "Uses")
    Rel(security, sign,"Uses")
    Rel(mbsfacade, books, "Uses")
}

Rel(spa, security, "Uses", "JSON")
Rel(spa, accfacade, "Uses", "JSON")
Rel(spa, mbsfacade, "Uses", "JSON")

Rel(ma, accfacade, "Uses", "JSON")
Rel(ma, security, "Uses", "JSON")
Rel(ma, mbsfacade, "Uses ", "JSON")
@enduml
