@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

title Диаграмма контекста

Person(techPerson, "Технический специалист", "Сотрудник, который хочет читать техническу литературу (разработка, тестирование, администрирование, дизайн)")
Person(managPerson, "Продажники", "Сотрудник, который хочет читать литературу связанную с тем, как нужно общаться с клиентом(организация беседы, представление продукта клиентам)")
Person(PM, "PM", "Сотрудник, который хочет читать литературу связанную с материальной частью(пр. строительством) и коммуникациям с клиентами")
Person(Trainer, "Наставник по развитию сотрудников", "Сотрудник, хочет назначить книгу для развития сотрудника назначенного на него")
Person(Admin, "Администратор, завхоз", "Сотрудник, ответсвенный за учет и хранение книг")
System(systemFrontAlias, "Библиотека", "Обработка данных")
ContainerDb(BD, "Database", "DB", "Хранилище книг и контактов")

Rel(techPerson, systemFrontAlias, "Сканирование QR-кода", "Назначение книги на себя")
Rel(managPerson, systemFrontAlias, "Сканирование QR-кода", "Назначение книги на себя")
Rel(PM, systemFrontAlias, "Сканирование QR-кода", "Назначение книги на себя")
Rel(Trainer, systemFrontAlias, "Выбор книгии сотрудника", "Назначение книги на сотрудника")
Rel(Admin, systemFrontAlias, "Просмотр списка книг и их статуса", "Просмотр статуса книг")
Rel(systemFrontAlias, BD, "Отправка запроса", "Обработка и вывод из БД данных")
@enduml