@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(personAlias, "Читатель", "Сотрудник, который хочет взаимодействовать с системой")
System(systemFrontAlias, "Система","Обработка данных")
ContainerDb(BD, "Database", "DB", "Хранилище книг и контактов")

Rel(personAlias, systemFrontAlias, "Сканирование QR-кода", "Отправка данных")
Rel(systemFrontAlias, BD, "Отправка запроса", "Отправка запроса")
@enduml